# redis container

redis:
  image: redis:3
  ports:
    - "32770:6379"

web:
  build: .
  volumes:
    - .:/app
  links:
    - redis:redis
  command: su -m myuser -c "docker run -it --rm -p 5000:5000 streamframework stream-framework-flask.py"
  depends_on:
    - redis
    - worker
worker:
  build: .
  links:
    - redis:redis
  volumes:
    - .:app
  command: su -m myuser -c "celery -A stream_framework.tasks worker -l debug --config celery"