# redis container

redis:
  image: redis:3
  ports:
    - "32770:6379"

web:
  build: .
  links:
    - redis:redis
  ports:
  - "5000:5000"
  command: ./stream-framework-flask.py
  user: myuser
worker:
  build: .
  links:
    - redis:redis
  command: celery -A stream_framework.tasks worker -l debug --config celery
  user: myuser
